# Mutation SignUp: email + password
mutation SignUp($email: String!, $password: String!) {
  register(input: { email: $email, password: $password }) {
    user {
      _id
      email
    }
    token
  }
}

# Mutation AddStream
mutation AddStream($input: StreamInput!) {
  addStream(input: $input) {
    _id
    title
    description
    url
  }
}

# Query Current User: _id + email
query CurrentUser {
  currentUser {
    _id
    email
  }
}

# Query Stream
query Stream($streamId: ObjectId!) {
  stream(streamId: $streamId) {
    _id
    title
    description
    url
    author {
      _id
      email
    }
  }
}
